### ISSUE TITLE
Requirment of the project!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Dymirt** [mazen-tech/Cub3dFinal#7]
To turn in bonuses to your project, you must include a rule bonus to your Makefile,
which will add all the various headers, librairies or functions that are forbidden on
the main part of the project. Bonuses must be in a different file _bonus.{c/h} if
the subject does not specify anything else. Mandatory and bonus part evaluation
is done separately.

**Comment by mazen-tech** [comment]
The version in branch main is now free of any code related to the bonus part. 
what has been removed 
-jump move
-some functions related to minimap
